### PR TITLE
Feedback animation

### PR DESCRIPTION
**Pull request by wcandillon**

### CODE REVIEW

**Comment by Angelk90** [comment]
@wcandillon : Hi, Congratulations, but I tried on Android seems not to work very well.

P. S.

Do you accept a proposal for a new video, with animation?

**Comment by wcandillon** [comment]
@Angelk90 Thank you!

I just tried the latest version on android and it seems to be working well for me. Could you provide me with more information about the issue?

Of course, I love proposals :)

**Comment by Angelk90** [comment]
@wcandillon : Do you accept as a challenge?

**Comment by wcandillon** [comment]
100% but I'm not sure about the timeline though, there are some examples
which I would like to do before. But let's see :)

**Comment by Angelk90** [comment]
@wcandillon : timeline? If you want, I can pass you some tests I tried to do if I find them.

**Pull request merged**
